name: caminante_appvsc
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_calendar: ^26.1.35
  table_calendar: ^3.0.8
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  pin_code_fields: ^8.0.1
  flutter_rounded_progress_bar: ^0.3.2
  smooth_page_indicator: ^1.1.0
  flutter_color: any
  pin_input_text_field: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  intl: any
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.2.1 #librería para activar desactivar notificaciones
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  flutter_rating_bar: ^4.0.0 # Usa la versión más reciente disponible
  qrscan: ^0.3.3 #libería para qr
  permission_handler: 11.3.1  #permisos par qr
  url_launcher: ^6.1.5






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/
